name: Build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '12.13'
        registry-url: 'https://registry.npmjs.org'

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: yarn install && yarn build